DEBUG:mikroeuhb.devkit:buffering 118908 of 118908 blocks DEBUG:mikroeuhb.devkit:writing 8 bytes to 0x1fc01180 Traceback (most recent call last): File "/usr/local/bin/mikroe-uhb", line 5, in <module> pkg_resources.run_script('mikroe-uhb==0.2', 'mikroe-uhb') File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script self.require(requires)[0].run_script(script_name, ns) File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1441, in run_script exec(script_code, namespace, namespace) File "/usr/local/lib/python2.7/dist-packages/mikroe_uhb-0.2-py2.7.egg/EGG-INFO/scripts/mikroe-uhb", line 58, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mikroe_uhb-0.2-py2.7.egg/EGG-INFO/scripts/mikroe-uhb", line 55, in main

  File "build/bdist.linux-x86_64/egg/mikroeuhb/device.py", line 137, in program
  File "build/bdist.linux-x86_64/egg/mikroeuhb/hexfile.py", line 28, in load
  File "build/bdist.linux-x86_64/egg/mikroeuhb/devkit.py", line 417, in write
  File "build/bdist.linux-x86_64/egg/mikroeuhb/devkit.py", line 115, in _write_phy
IndexError: invalid address 0x1fc01180
make: *** [test_load] Error 1